import Wrapper from '@/components/wrapper'
import Footer from '@/components/layouts/footer'
import Header from '@/components/layouts/header/header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Wrapper className="wrapper-class">
      {/* @ts-expect-error Server Component */}
      <Header />
      <div className="min-h-[80vh]">
        {children}
      </div>
      <Footer />
    </Wrapper>
  )
}
